### ISSUE TITLE
Unable to download the package

### ISSUE THREAD

**Issue by perrmadiafrrian** [kwoodhouse93/gotrue-go#1]
# Bug report

## Describe the bug

I'm was unable to `go get` the package. Resulting in an error like below
```
go: github.com/supabase-community/gotrue-go@v1.0.0: parsing go.mod:
        module declares its path as: github.com/kwoodhouse93/gotrue-go
                but was required as: github.com/supabase-community/gotrue-go
```

## To Reproduce

1. Init go `go mod init example`
2. run `go get github.com/supabase-community/gotrue-go`

## Expected behavior

This package successfully downloaded

## Screenshots
--

## System information

- OS: Ubuntu 20.04.3 LTS

## Additional context
--

**Comment by kwoodhouse93** [comment]
My apologies - this package was recently moved from `kwoodhouse93/gotrue-go` to `supabase-community/gotrue-go`, hence the issue where `v1.0.0` still thinks it lives at `kwoodhouse93`.

I previously released a new major version (`v2.0.0`), but that did not behave as I expected with Go modules. I've just created release `v1.0.1` instead, which should let you `go get` just fine without needing to specify a version.

It may take a minute for the public proxy cache to update, so if it still tries to fetch `v1.0.0`, please specify `go get github.com/supabase-community/gotrue-go@v1.0.1` and you should be good to go.
