### ISSUE TITLE
PKCE authorization

### ISSUE THREAD

**Issue by Qinbeans** [kwoodhouse93/gotrue-go#2]
# Feature request

PKCE authorization and code exchange.

## Is your feature request related to a problem? Please describe.

Not necessarily, but the code we're migrating utilized the PKCE feature in Supabase. PKCE offers some security bonuses over implicit, which is the current authorization method.

## Describe the solution you'd like

 In authorize.Authorize we can add a check for PKCE flowtype which adds 2 items into the query:

1. code_challenge
2. code_challenge_method

You can write a function to generate the required PKCE parameters. https://github.com/nedpals/supabase-go has a great implementation of this.

After a redirect has been executed, then the a callback function with Token must be executed where a parsed URL parameter is shoved into TokenRequest{ GrantType: "pkce", Code: "code", CodeVerifier: "verifier }.

Add a case for PKCE in token.Token to check for empty code or empty verifier. After that, the code should be serializable into a request so no other changes would need to be made.

## Describe alternatives you've considered

The existing form of authorize does work, but forgoes the potential security from PKCE

## Additional context

Here's my fork: https://github.com/Qinbeans/gotrue-go

If you're pleased with it, I'd be happy to pull request.

**Comment by kwoodhouse93** [comment]
Thanks for opening the issue. The code in your fork looks good to me. I'll find some time to test your changes locally too. In the mean time, can you open a pull request? And we can look at getting it merged soon after

**Comment by kwoodhouse93** [comment]
Merged now, I'll create a release tag. Thanks for your contribution!
