### ISSUE TITLE
Add callback similar to onAuthStateChange

### ISSUE THREAD

**Issue by elijahmorg** [kwoodhouse93/gotrue-go#5]
# Feature request

Add in a callback to the gotrue-go client interface so supabase-go can pass in callback. This is to follow the implementation in [supabase-js](https://github.com/supabase/auth-js/blob/master/src/GoTrueClient.ts#L1608).

I am happy to implement this if maintainers agree with overall concept.

Additional feature to this would be to add automatic token refresh via goroutine in gotrue-go.

## Is your feature request related to a problem? Please describe.

N/A

## Describe the solution you'd like

Mimic auth-js and add ability to pass in callback for when auth state changes. This would allow me to add a listener in my supabase-go work to listen for auth state changes and not have re-implement every interface to correctly update the clients token. You can see my current work on supabase-go this [pr](https://github.com/supabase-community/supabase-go/pull/9).

## Describe alternatives you've considered

Alternatively I can implement this in the supabase-go client and handle automatically refreshing tokens there, but that would break the pattern in auth-js. This just means the supabase-go client logic is a little heavier and maybe prone to later breakages?I think it could go either way.

**Comment by kwoodhouse93** [comment]
`auth-js` is designed as an isomorphic library, which is intended to be used on both client and server. To date, given `gotrue-go` is more likely to be used on a backend server, it has been designed simply as a convenient way to interact with a gotrue server (i.e. with a properly typed API). That's the reason you don't see any callback/subscription or token refresh functionality, as you see in `auth-js`.

While we could add session management to this library, my starting position is that it would be preferable to introduce it as a separate library. Those intending to interact with a gotrue server from a backend server can then continue to use this relatively lightweight package, while those also intending to use any session management features would still be free to make use of a separate package which introduces that functionality.

I'd caveat that by saying I've not looked into how the implementation would work, so I'm not yet certain whether there are any technical limitations to keeping these separate. I'd encourage you to start by building session management and callbacks as a separate package, and report back if you hit any roadblocks along the way.

**Comment by elijahmorg** [comment]
Thanks for the thorough reply! This makes sense. I'll add some sort of mechanism into the supabase-go module instead.
