### ISSUE TITLE
Rename repo to `auth-go`

### ISSUE THREAD

**Issue by acomanescu** [kwoodhouse93/gotrue-go#7]
# Feature request

## Is your feature request related to a problem? Please describe.

To keep in sync with the new naming, please rename this repo.

## Describe the solution you'd like

We should have this repo as `auth-go`

## Describe alternatives you've considered

-

## Additional context

-

**Comment by kwoodhouse93** [comment]
As a Go repo, renaming the repo would be a breaking change for all users.

I'd suggest the following as a way to achieve this without causing massive inconvenience to anyone using this package:
1. Clone this to a new repo with the new name
2. Make the necessary breaking change updates there (renaming the package and updating all imports)
3. In this repo, add a link to the new one
4. Archive this repo (crucially, it must remain publicly available)

We can do that, but I don't have the ability to create new repos under the @supabase-community org, so I'll need to find out who can.

If moving to a new repo, I'm not sure what Github preserves when duplicating a repo, but we may lose some release, PR and issue history in the move.

**Comment by kwoodhouse93** [comment]
Please see [supabase-community/auth-go](https://github.com/supabase-community/auth-go) - it is now the main client library for Supabase auth.

This repository will shortly be archived. Apart from exceptional circumstances, this repo will no longer receive updates. Further support and updates will be made to [auth-go](https://github.com/supabase-community/auth-go) instead.

Closing this issue as resolved.

---

For some extra context on this decision:
1. This library is very simple - it effectively makes HTTP requests and unmarshals the responses to a set of known types
2. Very little maintenance has been needed so far - a few feature requests have been accommodated, but no bugs have been raised
3. I am currently the only active maintainer, and I don't have much time to spare on this

Given the first two points, I anticipate the likelihood of urgent fixes being needed on `gotrue-go` to be quite low. Therefore, and given the limited time available for maintenance, it is better to focus on a single repository going forward.

If this decision causes you undue difficulty, please raise it with me by creating an issue in the [auth-go repo](https://github.com/supabase-community/auth-go/issues/new/choose) and we can discuss a way forward. The intention is not to cause pain for anyone, but to keep the maintenance burden contained.
